# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qcT393YX1pbwZwYpDvP+2bf95CX6uiCADbK8j8jFA8OK/dHX0nMYU8RU7Zt++rF3GXrIQ7awtLT+aniQquqoWfjwlvVeCkmTUYfRb0qRz837pcAecoe7gBRY+I1joztQIO1km2gGc3RlO4G1gRvqg9d7Eoe3LKJoCm+b7FJ201UXbqZ0Q5kwlJldrUNzrdhdN56Hm7E8aNJcZA9HCl+z98fyE5/Z46++BMzFxAOS8VKQq4OpWUm6S6jjR8eM4jHuYMhcqfog4ClvELKwyM9p7ujWFxSP2D+p9CiuWM9dfEDOmWzR0GGZ+/vG+bZ8fUw65xW8FzM2elFgSwbrB8LDvwNQfCJGObdm+HBreGkvwrgCwuPvKvSw/0zIXeFjoBLtEu6lg8W1eKJUsU3Ffnxxf2fbydU92xh7+Kcc3yU3Tql7CCCrrzESae4a89wXV2s9zZe1HcmGGJA/sNQ14QJ+pM3czkDE6qCtvdKF4Xihfdf8mLqD2/rDNGchVrq9e9juemlv9urWK3Hr1KgeVOuua7CZCD+ymzPODZUSj76xog/0Fz88RB6w3llxqAR9GZ6bn9EGKG/cWn78hJ2oBytC70qhrNbr1gTQH6PfUd/cNQBPJ4wnRr7zpkpnXOBi/QwDB+S6f2LuGlGWp1Rwvy3wkgpko12WSpaZ/qv4nMOZxpc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
