travis:
  secure:
    BINSTAR_TOKEN: MfM3a9ZBJRbTQSaaIIiwxpf4wnO231pyj3nVN7ZmDg06fYHAAnC5RlZKACTLOrVr9pDbXC9fKrBuZmWYmCQ0kMQsJz7WeSdeiy3cwXRz+FFEE4suFhqaNBvdLJ2KDZo8sZo13zvCq+PTGzNYyoo8T4IzHFVeT7CxA/Le0t3cckVJBrjnBhZ7D+3IRjZ1x4AK6bE2ZgKe6zBDJAc7D8xdWOpbUHiVo1DrOBz+nclX+exC28pT50tOCcn23xRylO/dpqn2ONX2PR5wMZft+OlQYiPQRYGa+5jrIvaidtPts1VaUmpWzMR3Dh1kwRrBO+j5zekOz1RlYrjCF7qKRrTjmJVKystBfUwrjeKcdnYInnbbeiUXeIu9IiaRhMj2FJUl482//JkgjUZKEYP2yaGJ+bWnpDX2SF2yuBnITm3usZoqN0d0pHUO3TF60Ft5ReOZ8X0HLIhdrrSCJys3aar71romCrzBvFilVIcLO+uQ6PGKF+VC5X8161scf6GU4dyAsJhSM7HeINi3yKGddKH9WkFUpHlA2Sk3qrMCtwnhN+QDj4pH/hZ8z40jPESg7qfRx+xzhykyhkrJX0F2DmxEPpDlHatuNE7f4006AoK6HKrugKDXkWwlNzImi72o1Sr1Moo/ioQXsfGp2GHwlACAgTFkSNfUfS5AWy4GgNFzTUM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
